### ISSUE TITLE
Bad format on resolve message.

### ISSUE THREAD

**Issue by mihalby** [slok/alertgram#31]
![изображение](https://user-images.githubusercontent.com/46110854/102528843-24c14600-40b0-11eb-9156-328600d688fc.png)

I think resolve message is uninformative. Pls help me if it possible.
Thx.

Use docker container for alertgram with minimal options.
Alert manager version:
Branch:
HEAD
BuildDate:
20200617-08:54:02
BuildUser:
root@dee35927357f
GoVersion:
go1.14.4
Revision:
4c6c03ebfe21009c546e4d1e9b92c371d67c021d
Version:
0.21.0

**Comment by slok** [comment]
Hi @mihalby!

Yes, that's the main problem, that the resolved alerts are not being rendered. You could create your own template and load it on execution, however, I'll add support for `resolved` on the default template.

**Comment by slok** [comment]
Hi @mihalby!

I just released `v0.3.2`, You can use `slok/alertgram:v0.3.2` image.

Best!
